### ISSUE TITLE
3.0.7 doesn't work under Big Sur

### ISSUE THREAD

**Issue by webcoderkz** [browserpass/browserpass-native#101]
### General information

-   MacOS Big Sur
-   Chrome 86:
-   Information about the host app:
    -   How did you install it?
    -   Installed with homebrew: `Browserpass host app version: 3.0.7`
-   Information about the browser extension:
    -   How did you install it?
    -   From chrome webstore
    -   Browserpass extension version as reported by your browser: 3.7.1

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

- Not related to my case

---

### Exact steps to reproduce the problem

1. Click on the browserpass icon in the google chrome
2. Error message would pop up: "Error: Error: Specified native messaging host not found."

### What should happen?

It should let me choose an account with data, as it was in catalina.

### What happened instead?

![image](https://user-images.githubusercontent.com/5739191/99154922-bfa7b880-26dd-11eb-9617-6bec79a42548.png)

**Comment by maximbaz** [comment]
Hi, I think the configure browsers is very much related to your case 😉

**Comment by webcoderkz** [comment]
I've read it, but couldn't get it, could you please point me in a right direction, on what i did wrong?

**Comment by maximbaz** [comment]
you need to replace `BROWSER` with one of the values, so for example `PREFIX .... make hosts-chromium-user ....` if you use Chromium

**Comment by webcoderkz** [comment]
chromium and chrome - is there a difference? i'm actually using a chrome. Just noticed this warning, lol :)

**Comment by maximbaz** [comment]
There is a difference, yes, if you use Chrome then use `chrome` :)
