### ISSUE TITLE
Support for Opera Browser

### ISSUE THREAD

**Issue by Bluesboy** [browserpass/browserpass-native#105]
### General information

-   Fedora 33:
-   Opera 77.0.4054.64:
-   Information about the host app:
    -   Built from source (0997aee)
-   Information about the browser extension:
    -   Installed form Chrome Extension Store

Getting "Error: Error: Specified native messaging host not found." in popup and extension settings

**Comment by maximbaz** [comment]
I transferred the issue to the relevant repo. See `Makefile` in the root of the repo, it contains support for different browsers. You can look at various browsers and you would be able to make some educated guesses where Opera might be storing its config files, or try to search for some Opera documentation.

Ideally, you would need to create 4 new sections by example of the other browsers: `hosts-opera`, `hosts-opera-user`, `policies-opera`, `policies-opera-user`. 

The former two are for configuring the browser (what you are missing in your setup), the latter two help installing the extension (if you place the policy correctly, it will make Browserpass look like "pre-installed" extension, it will look like it cannot be removed, and if it was not there, it would "magically" install it).

It might be easier if you play with those make targets using one of the already supported browsers, e.g. if you dont have Browserpass configured in Chromium, play with chromium targets to see how it works.

And good luck! 🙏

**Comment by Bluesboy** [comment]
@maximbaz Thank you very much! Turned out that for Opera you can use `hosts-chrome` target, not sure about user policies `policies-chromium-user` worked for me, not sure, though, maybe it not needed at all.

**Comment by maximbaz** [comment]
Interesting! OK good that it works, I'll add this to README :)
