### ISSUE TITLE
AppImage Build

### ISSUE THREAD

**Issue by trev-dev** [browserpass/browserpass-native#109]
Yes, everyone has their opinion of which universal packaging solution works best for various reasons. The one universal packaging system that I've interacted with that's never caused me any problems and may be well suited for this project is AppImage

Docs: https://docs.appimage.org/introduction/index.html

I would take this as a learning opportunity and contribute if enough people can agree that they'd use it.

**Comment by erayd** [comment]
What purpose would be served by packaging the native host as an AppImage? It's *already* a single binary, and given that it's written in Go, it's statically compiled and has no runtime dependencies to distribute.

**Comment by trev-dev** [comment]
Guess I could've looked at the releases, eh? I saw no quick instructions for Fedora/RPM and assumed that I'd have to build from source. I'd happily grab a compiled x86_64 binary.
