### ISSUE TITLE
Error: Specified native messaging host not found on WSL2

### ISSUE THREAD

**Issue by kimyoungmichael2** [browserpass/browserpass-native#110]
### General information

-   Operating system + version: Windows 10 Pro Build 19043 64 bit | WSL2 Ubuntu 20.04 LTS
-   Browser + version: Chrome 92.0.4515.131 (Official Build) (64-bit)
-   Information about the host app:
    -   Windows: downloaded latest release for `windows64` on https://github.com/browserpass/browserpass-native/releases
    -   WSL2: downloaded latest release for 'linux64' on https://github.com/browserpass/browserpass-native/releases. Followed instructions on https://github.com/browserpass/browserpass-native/issues/78 to install. 
    -  Both Versions 3.0.7
-   Information about the browser extension:
    -   How did you install it? Installed through Chrome Web Store.
    -   Browserpass extension version as reported by your browser: 3.7.2

### Exact steps to reproduce the problem

I followed the WSL instruction on https://github.com/browserpass/browserpass-native#installation: 
- For Windows, download and run the install file at https://github.com/browserpass/browserpass-native/releases
- For WSL2, I downloaded `linux64` version from the same link and installed locally by running `make BIN=browserpass-linux64 configure` and `sudo make BIN=browserpass-linux64 install` in the directory with the Makefile
- I created `C:\Program Files\Browserpass\browserpass-wsl.bat` and copied the content as mentioned in the instruction.
- I edited `chromium-host.json` file and updated the "path" key value to: `"path": "C:\\Program Files\\Browserpass\\browserpass-wsl.bat"`

### What should happen?
My Chrome running in Windows should connect with the browserpass native host running in WSL2. 

### What happened instead?
The browserpass extension gives `Error: Error: Specified native messaging host not found.` error. 

Hello, I've been struggling to make this work for some time and would appreciate any sort of help. I feel like I have followed the provided instruction as best I can at this point, but I cannot seem to get it to work. Thank you in advance,

**Comment by maximbaz** [comment]
Hello, sorry to hear that you are having troubles with this. As far as I can tell you are doing everything correctly, but WSL instructions were always contributed by community, I've never actually tested them myself. Consider searching for "WSL" in this or "-extension" repo to see folk who was active and politely pinging them here asking for help. I hope you'll get this solved, and once you do, please feel free to send a PR updating the instructions!

**Comment by kimyoungmichael2** [comment]
Thank you, I'll try what you suggest for now.

**Comment by kimyoungmichael2** [comment]
I really feel like smacking myself in the head right now. The problem I had was I created the .bat file as a Windows text document (.txt); I thought naming it .bat will make Windows believe it's a batch file, but it didn't 🤦‍♂️
The person who submitted https://github.com/browserpass/browserpass-native/issues/92 was kind enough to post some screen shots, which made me realize my mistake. Browserpass is working fine now through WSL2. 
Thanks for your help!
