### ISSUE TITLE
Support Firefox snap package

### ISSUE THREAD

**Issue by wmortada** [browserpass/browserpass-native#112]
### General information

-   Operating system + version: Ubuntu 21.10
-   Browser + version: Firefox 94.01 snap for Ubuntu canonical-002 - 1.0
-   Information about the host app:
    -   How did you install it? Installed via a package manager (`apt install webext-browserpass`)
    -   If installed an official release, put a version (`$ browserpass --version`): 3.7.2-1
    -   If built from sources, put a commit id (`$ git describe --always`):
-   Information about the browser extension:
    -   How did you install it? Installed via [webstore](https://addons.mozilla.org/en-US/firefox/addon/browserpass-ce/)
    -   Browserpass extension version as reported by your browser: 3.7.2

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

---

I think this is the same issue as #82. Ubuntu is now supplying Firefox as a snap package and browserpass no longer works.

### Exact steps to reproduce the problem

1. Click on the browserpass icon in Firefox

2. See an error message: "_Error: Error: Attempt to postMessage on disconnected port_"

### What should happen?

Browserpass should work with Firefox.

### What happened instead?

Browserpass doesn't work with the snap version of Firefox.

**Comment by maximbaz** [comment]
I agree that the issue is indeed very similar, hopefully solving one would solve the other 🙂

**Comment by mrtndwrd** [comment]
The snap package is now the default in Ubuntu 22.04 so it just started failing for me after upgrading my Ubuntu to the newest LTS. Please let me know if I can do anything to provide useful information.

**Comment by maximbaz** [comment]
Please see the linked Chromium thread, you'll find some info about what people tried and what is missing to get this issue solved.

**Comment by mrtndwrd** [comment]
I actually remember that thread from 2019 :sweat_smile: But to be honest I don't know how to help by looking at that issue. I'm neither a Go nor a Snap developer, so the best I can do right now is provide logs and that kind of information and try already suggested workarounds.

**Comment by mrtndwrd** [comment]
For now I reverted to deb-style Firefox by following [these instructions](https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04). I can confirm that browserpass works again :)

**Comment by tmerten** [comment]
I did not try this myself yet but for the curious, there is a [call for testing with respect to native messaging support in the Firefox snap](https://discourse.ubuntu.com/t/call-for-testing-native-messaging-support-in-the-firefox-snap/29759).

**Comment by tmerten** [comment]
And now I did test it. Running 22.04.1, default Gnome/Wayland:

```
apt remove firefox
mv ~/.mozilla some-backup # might not be necessary

# remove all the apt overriding
rm /etc/apt/apt.conf.d/51unattended-upgrades-firefox
rm /etc/apt/sources.list.d/mozillateam-ubuntu-ppa-jammy.list
sudo rm /etc/apt/preferences.d/mozilla-firefox

# install beta snap and add native messaging app
snap install firefox --beta
cd /usr/lib/browserpass && make hosts-firefox-user
```

After starting and installing browserpass from firefox addons I had to allow calling the native messaging app once. And here we go:

![browserpass-snap](https://user-images.githubusercontent.com/3410703/187023213-dd1dbd00-4b70-4750-b127-3fe53366b086.png)

**Comment by adamschoenemann** [comment]
After install snap firefox beta, if you don't get a popup dialog asking for native messaging permissions for browserpass, run this command after closing firefox:

`flatpak permission-set webextensions com.github.browserpass.native snap.firefox yes`

**Comment by maximbaz** [comment]
Do I understand correctly that this issue is now solved and can be closed? :tada:

**Comment by wmortada** [comment]
Sorry for the delay in replying. Yes, this is working for me now. Thanks!

- Ubuntu 22.04.3
- Firefox 119.0
- Browserpass 3.8.0
