### ISSUE TITLE
Brave browser -  Error: Specified native messaging host not found.

### ISSUE THREAD

**Issue by rere-dnaw** [browserpass/browserpass-native#114]
### General information

-   Operating system + version: Zorin OS 16 x86_64 
-   Browser + version: Brave Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-   Information about the host app:
    -   How did you install it?
          downloaded a pre-built binary
    -   If installed an official release, put a version 
          (`$ browserpass --version`): browserpass: command not found   
          (`$ browserpass-linux64  --version`): Browserpass host app version: 3.0.7
    -   If built from sources, put a commit id (`$ git describe --always`):
-   Information about the browser extension:
    -   How did you install it?
        webstore
    -   Browserpass extension version as reported by your browser: 
        3.7.2
---
If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?
---
I did follow. I tried: make hosts-brave-user and sudo make hosts-brave

### Exact steps to reproduce the problem

1. make BIN=browserpass-linux64 configure

2. sudo make BIN=browserpass-linux64 install

3. I tried: make hosts-brave-user and sudo make hosts-brave

4. Install extension.

### What should happen?
The extension should be connected to host.

### What happened instead?
Error: Error: Specified native messaging host not found.

```
PC:/usr/lib/browserpass$ ls -R
.:
browserpass-native  hosts  Makefile  policies

./hosts:
chromium  firefox

./hosts/chromium:
com.github.browserpass.native.json

./hosts/firefox:
com.github.browserpass.native.json

./policies:
chromium

./policies/chromium:
com.github.browserpass.native.json
```

**Comment by maximbaz** [comment]
Hi there 👋 

It's most probable that some (all) of these paths are incorrect, last time I used Brave 3 years ago, and maybe they have updated something since. There is no good way to know these directories, some browsers document them, in others we just find them by trial and error. Community effort is often driving this, and help is very welcome! If you know of any other extension that uses native host and that works for you, it will be quite helpful as you can just peek where they installed the hosts files :)

https://github.com/browserpass/browserpass-native/blob/d73f45c5a1c581381cfc7d2d564b521d65988c1e/Makefile#L439-L440

https://github.com/browserpass/browserpass-native/blob/d73f45c5a1c581381cfc7d2d564b521d65988c1e/Makefile#L453-L454

This old comment of mine doesn't inspire confidence either 😅 

https://github.com/browserpass/browserpass-native/pull/26#discussion_r264935527

**Comment by rere-dnaw** [comment]
hi,
Thanks for the reply :) I think you are correct about the problem with paths. I did try some other pass extensions which are using native host but they didn't work with brave browser as well (or I was doing something wrong :P). Also I tried to use other paths instead but no luck there.

**Comment by tejing1** [comment]
I have no idea if this is still an issue for anyone after over a year, but I'm using browserpass with brave without an issue on nixos+home-manager. These lines from my home-manager config should be fairly self-explanatory even if you don't know anything about nix:
```nix
{
  home.file.".config/BraveSoftware/Brave-Browser/NativeMessagingHosts/com.github.browserpass.native.json".source = "${pkgs.browserpass}/lib/browserpass/hosts/chromium/com.github.browserpass.native.json";
  home.file.".config/BraveSoftware/Brave-Browser/policies/managed/com.github.browserpass.native.json".source = "${pkgs.browserpass}/lib/browserpass/policies/chromium/com.github.browserpass.native.json";
}
```
Hope it's helpful regarding the locations brave is searching.

**Comment by maximbaz** [comment]
Thanks for confirming that these paths are working! These do seem to be exactly what we have in our Makefile today. Let's close this issue, and if at any point the paths need to be updated, just send out a PR, as those are completely community-driven!

**Comment by ualich** [comment]
This error also occurs when Brave Browser is installed with snap, as browser config files are not stored in `~/.config/BraveSoftware` in this case.

**Comment by maximbaz** [comment]
Let's keep track of snap packages separately, feel free to create a new issue if you want, but probably following the #82 would be enough, as brave is based on chromium
