### ISSUE TITLE
Native component on M1-based apple device not supported

### ISSUE THREAD

**Issue by finwo** [browserpass/browserpass-native#116]
### General information

-   Operating system + version: macOS Monterey (12.2), on macbook air with M1-based processor
-   Browser + version: Firefox 96.0.3 / 97.0
-   Information about the host app:
    -   How did you install it?
        - `brew install amar1729/formulae/browserpass` (uses release binaries from this repository)
        - `PREFIX='/opt/homebrew/opt/browserpass' make hosts-firefox-user -f '/opt/homebrew/opt/browserpass/lib/browserpass/Makefile'`
    -   If installed an official release, put a version (`$ browserpass --version`): 3.0.7
    -   If built from sources, put a commit id (`$ git describe --always`): n/a
-   Information about the browser extension:
    -   How did you install it?
        - Through https://addons.mozilla.org/en-US/firefox/addon/browserpass-ce/
    -   Browserpass extension version as reported by your browser: 3.7.2

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

Yes, I have, as shown in the 'install' explanation

---

### Exact steps to reproduce the problem

1. Install homebrew on M1-based apple device
2. Install pass using `brew install pass`
3. Install the native component of browserpass using `brew install amar1729/formulae/browserpass` (using bare `brew install browserpass` is not supported yet by homebrew on M1 devices)
4. Attempt running `browserpass-darwin64` using the command line, which'll result in the message `zsh: bad CPU type in executable: browserpass-darwin64`

### What should happen?

The browserpass native component should run as it would on x86-based machines.

### What happened instead?

The executable did not run

---

Based on quickly looking at the Makefile, including darwin64-arm64 in the release files, like is the case with other platforms, would allow homebrew (or other formulae providers) to fix this in their packaging without resorting to setting up a custom pipeline.

**Comment by maximbaz** [comment]
I agree that I should add the `darwin-arm64` binary to the release, however please be aware of two things:

1. The brew tap right now [anyway downloads the x86 binary](https://github.com/Amar1729/homebrew-formulae/blob/2eb9750d09a94d0a155ed58e56cf376d5e64ed48/browserpass.rb#L4), that will need to be adapted, if at all possible without making a separate tap (should be, right?)
2. The current tap actually works just fine for me on M1 processor, and seems line works [for other people too](https://github.com/Amar1729/homebrew-formulae/issues/9). Maybe you need to install rosetta? (I nevertheless agree that using native binary is preferred over x86 binary with rosetta)

**Comment by maximbaz** [comment]
3.0.8 published with pre-built binary for M1 👍
