### ISSUE TITLE
Firefox: Error: Specified native messaging host not found.

### ISSUE THREAD

**Issue by tnetsch** [browserpass/browserpass-native#125]
### General information

-   MacOS 11.6.7 (Big Sur)
-   Chrome 103.0.5060.134 and Firefox 103.0
-   For the host app I used source distribution `browserpass-darwin64-3.0.7.tar.gz` 
-   For browser extension I used the the official extension store both for Chroma and Firefox, version 3.7.2

---
If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

- Yes.
- I have also checked the issues (message pops up in some discussion). I have installed the extension some time ago for Chrome and Frirefox, these days I wanted to include also Firefox browser and just installed the extension which did not work as expected. Please note, Chrome installation was straightforward following the instructions. Plugin and host communication just worked immediately.
---

### Exact steps to reproduce the problem 

* Using MacPorts to match dependencies `coreutils` and `gsed`.
* Then I installed everything:
```
cd Software/pass/browserpass-darwin64-3.0.7
make BIN=browserpass-darwin64 PREFIX=/Users/thomas/usr configure
make BIN=browserpass-darwin64 PREFIX=/Users/thomas/usr install
```
* Made connections:
```
cd /Users/thomas/usr/browserpass
make PREFIX=/Users/thomas/usr hosts-chrome-user
make PREFIX=/Users/thomas/usr policies-chrome-user
make PREFIX=/Users/thomas/usr hosts-firefox-user
```
* Installed Chome extension and set path for the `gpg` binary to the MacPorts binary (in the Options menu), also added in my `pass` applications the `.browserpass.json` (which points to the same binary). 
* [Chrome password store works now.]
* [Few month later] Installed Firefox extension.

### What should happen?

[Firefox] I want to see the possible entries of my `pass` Password-Store when clicking on the Browserpass icon (as I see it when do the same in Chrome).

### What happened instead?

[Firefox] When I click on the Browserpass icon I see the message `Error: Error: Specified native messaging host not found.` in the popup. The message is also seen extension's configuration pane.

I do not understand this, I think I just have missed something ...

**Comment by tnetsch** [comment]
... indeed, it just literally followed the message of the error and checked the `ApplicationSupport` for Mozilla and I recognized the `NativeMessagingHost` directory was not there. The reason for this is, that I completely removed Firefox and re-installed Firefox before I added Browserpass. Hence running the `make` again, solved the issue.

Now everything's work as expected.

You may close / delete the issue, my apologies for brining it to attention.

**Comment by maximbaz** [comment]
Glad you solved it so fast, enjoy!
