### ISSUE TITLE
Symlink points to a non-existent location

### ISSUE THREAD

**Issue by krossgear** [browserpass/browserpass-native#126]
### General information

-   Operating system + version: **Debian 11** (QubesOS AppVM)
-   Browser + version: **Brave Browser (104.1.42.86)**
-   Information about the host app:
    -   How did you install it? **Installed via a package manager**
    -   If installed an official release, put a version (`$ browserpass --version`): **3.7.2-1+b4**
-   Information about the browser extension:
    -   How did you install it? **webstore**
    -   Browserpass extension version as reported by your browser: **3.7.2**

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section? **N/A**

---

### Exact steps to reproduce the problem

1. install _webext-browserpass_ package from the Debian stable repository via `sudo apt install`

2. install extension on Brave Browser from the chrome store

3. `cd /usr/lib/browserpass`

4. `sudo make hosts-brave-user` OR `sudo make hosts-brave`

### What should happen?

`/home/user/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/com.github.browserpass.native.json` should successfully link to `/usr/lib/browserpass/hosts/chromium/com.github.browserpass.native.json`

### What happened instead?

`Error: the symlink points to a non-existent location`

`/usr/lib/browser/hosts`...does not exist

**Comment by krossgear** [comment]
decided not to use extension

**Comment by erayd** [comment]
@maximbaz Is this issue ours to fix, or the debian packager?

**Comment by maximbaz** [comment]
To be honest hard to say, almost all browsers were contributed by community, we haven't tested them, so either package installs something in a wrong place, or browser changed location, or it was contributed incorrectly...

**Comment by erayd** [comment]
If they aren't tested, then I wonder if it might be worthwhile for us to add a "does this file / directory exist" sanity check to our host recipes. That wouldn't actually *fix* anything, but we could at least inform the user that our recipe doesn't match their system, and hopefully prompt a bug report so that we can address it.

**Comment by maximbaz** [comment]
Ah sorry I may have read the issue incorrectly - we do expect the json files to be present at a certain location, so if they are truly missing, most probably it's the package issue (or maybe in reality, a matter of using the same `PREFIX` when calling `make hosts-*` as was used by the package).  In any case, the default Makefile installs them to `/usr/lib/browserpass/hosts`, not `/usr/lib/browser/hosts` - but that might have been a typo on OP's side. `PREFIX` can adjust that location.

What's contributed by community is location of _symlinks_ for a given browser on a given OS. We can't realistically test or warn users whether these locations are correct, and even if they aren't, it would take another friendly community person to actually find out what's the correct location for that particular OS+browser 🙂

**Comment by remilieam** [comment]
I have the same issue. When I install the host app using `sudo apt install webext-browserpass`, `ls /usr/lib/browserpass` only return `browserpass-native  Makefile`. No `hosts` folder

**Comment by externalxdpro** [comment]
> I have the same issue. When I install the host app using `sudo apt install webext-browserpass`, `ls /usr/lib/browserpass` only return `browserpass-native Makefile`. No `hosts` folder

Same for me as well.

**Comment by maximbaz** [comment]
Hello, we are not in control of Debian's package, so we cannot unfortunately help investigating and fixing this issue. Would some of you report this on [Debian's bugtracker](https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=webext-browserpass;dist=unstable)?

An alternative to unblock you guys might be to uninstall `webext-browserpass` and install the app manually by following [our installation instructions](https://github.com/browserpass/browserpass-native/tree/master#install-manually).

I'll add to README that Debian's pkg cannot be used for anything except Chromium and Firefox, but other than that I'm afraid this issue is not really actionable for us...

**Comment by stefanct** [comment]
FWIW, this fixes the issue for the google-provided `google-chrome-stable` in Debian Bookworm (12):

    ln -s /etc/chromium/native-messaging-hosts/com.github.browserpass.native.json /etc/opt/chrome/native-messaging-hosts/com.github.browserpass.native.json

**Comment by alliruk** [comment]
Google has explained where chrome looks for the manifest json file, so you can symlink depending on system wide or user specific installation: https://developer.chrome.com/docs/extensions/develop/concepts/native-messaging

**Comment by maximbaz** [comment]
And those paths are already reflected in the [Makefile](https://github.com/browserpass/browserpass-native/blob/master/Makefile), so simply finding your browser in [Configuring browsers](https://github.com/browserpass/browserpass-native#configure-browsers) section and executing the corresponding make target should be sufficient :wink: (and if you find a discrepancy, please file a PR!)
