### ISSUE TITLE
Browserpass working in librewolf but not in firefox

### ISSUE THREAD

**Issue by eauchat** [browserpass/browserpass-native#128]
### General information

-   Operating system + version: ubuntu 22.04
-   Browser + version: firefox 105.0.2 and librewolf 105.0.1-1
-   Information about the host app:
    -   How did you install it?
        Manually (downloaded tar file, ran make configure and make install commands)
        tar file version: browserpass-linux64-3.0.10.tar.gz
-   Information about the browser extension:
    -   How did you install it?
        browser webstore (both firefox and librewolf)
    -   Browserpass extension version as reported by your browser: 3.7.2 (both firefox and librewolf)

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

Yes

---

### Exact steps to reproduce the problem

1. Install `browserpass-native`
2. Run: `make hosts-librewolf-user`
3. Run: `make hosts-firefox-user`
4. Install `browserpass-extension` in librewolf
5. Install `browserpass-extension` in firefox

### What should happen?

browserpass should work in both browsers

### What happened instead?

browserpass works only in librewolf
In firefox, when trying to use the extension, I get the following message: `Error: Error: Attempt to postMessage on disconnected port`

Some more context on the issue, in case it's somehow related.
I already had browserpass installed in firefox, and after a system upgrade it wasn't working anymore (with the message mentioned in the previous lines).
Since it wasn't working, I reinstalled browserpass-native, and after seeing it was working in librewolf, I tried removing and readding the app in firefox, but it didn't improve the situation.

Any one may have an idea where the issue could be coming from?

**Comment by erayd** [comment]
> Any one may have an idea where the issue could be coming from?

It looks like you may have run into https://github.com/browserpass/browserpass-native/issues/112. The snap package that Ubuntu ships cannot see the native host, which lives outside of it.

You may find [these instructions](https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04) useful in working around the limitation.

**Comment by eauchat** [comment]
Oh ok, I missed that one. Then I guess I'll close this issue in favor of #112.
