### ISSUE TITLE
Error: Error: No such native application com.github.browserpass.native when launching librewolf via bwrapper

### ISSUE THREAD

**Issue by formula-spectre** [browserpass/browserpass-native#136]
### General information

-   Operating system + version: gentoo
-   Browser + version: librewolf 114.0.1-2
-   Information about the host app:
    -   How did you install it? installed via pacman
-   Information about the browser extension:
    -   How did you install it?
        via home-manager
    -   Browserpass extension version as reported by your browser: 3.7.2

---
I have an artix root, which I use bwrapper to run librewolf on my gentoo system, via this script:
`#!/bin/sh`
`[ "${0##*/}" = "bwrapper" ] || set -- "${0##*/}"`
`bwrap --bind /zartix / \`
`--dev-bind /dev /dev \`
`--bind /sys /sys \`
`--bind /proc /proc \`
`--bind /nix /nix \`
`--bind /run /run \`
`--ro-bind /run/user/"$(id -u)"/pulse /run/user/"$(id -u)"/pulse \`
`--bind /tmp /tmp \`
`--setenv DISPLAY ":1" \`
`--bind "${HOME}" "${HOME}" \`
`"${1}"`  

when launching librewolf via that, I get the error: `Error: Error: No such native application com.github.browserpass.native`

---

### Exact steps to reproduce the problem

1. get an arch/artix root

2. install librewolf inside the ar* root

3. modify the first line of the bwrap script to match the location of the ar* root, and then launch it via `bwrapper librewolf`

### What should happen?
the extension should work as expected

### What happened instead?
when clicking on the extension's icon, I get `Error: Error: No such native application com.github.browserpass.native`

---

let me know if the situation is clear and if more information is needed!

**Comment by maximbaz** [comment]
Hello, thanks for the report. I would probably not have the time to install the environment necessary to reproduce the issue, maybe it would be helpful if I lead you on the investigation on your side? 

Judging by the error message, the browser extension cannot find the native host. 

Have you followed these steps to set the connection up? 

https://github.com/browserpass/browserpass-native#configure-browsers

If no, that could be a missing link. 

If yes, maybe your isolated browser doesn't have the necessary bind for the location of the browser native host executable? You will find in the Makefile the necessary paths, see the librewolf target. 

Let me know how it went!

**Comment by maximbaz** [comment]
This issue was for a different browser, feel free to open a new one.

Browsers support is maintained by community, if you can follow the steps outlined above and find the correct location for the json files for your browser, please feel free to send a PR directly, I'll merge it. Otherwise we'll need to wait until other users of the same browsers would investigate this and submit a PR 🙂
