### ISSUE TITLE
Message saying "Update native host app" on an installation using package manager

### ISSUE THREAD

**Issue by morciej** [browserpass/browserpass-native#139]
### General information

-   Operating system + version: **Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy**
-   Browser + version: **Firefox 119**
-   Information about the host app:
    -   How did you install it? **Installed via a package manager**
    -   If installed an official release, put a version: **3.0.7**
-   Information about the browser extension:
    -   How did you install it? **addons.mozilla.org via extension manager**
    -   Browserpass extension version as reported by your browser: **3.8.0**

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section? **N/A**

---

### Exact steps to reproduce the problem

1. Install host app via package manager

2. Install browser extension

3. Click browser extension icon

### What should happen?

No message

### What happened instead?

Persistent message in red saying **"Update native host app: instructions"**

_Obviously, since the installation is by package manager and browser webstore, there is no way (or so far, need) to tweak versions unless I were to install manually._

_It's just an annoyance, as the extension otherwise works. So far._

**Comment by maximbaz** [comment]
Hello, thanks for making a post! We are generally not in control of the package maintenance in distro repos, with very few exceptions (e.g. I maintain Arch pkgs). 

The message is there exactly to notify you as a user, that you are missing out on new functionality because you are using outdated software. 

I'd recommend either reaching out to maintainer of the distro package, or installing the latest version manually. 

For your reference, 3.0.7 was released in 2020!

**Comment by morciej** [comment]
Ah the perennial Debian issue.

I am interested to find out what actually needs to be done. **Can I roll back the extension to match the webext-browserpass package version?** The older version seems to be downloaded by the package manager, but is ignored by Firefox.

Given that this is a production system (i.e. I do my taxes etc. on it) I am not willing to install bleeding edge software on it whatever it may offer. The extension works as is, and the alert is just an annoying way to rub in that I am only running stable software on this system.

**Comment by morciej** [comment]
The manually installed version works and the message is gone.

**Comment by maximbaz** [comment]
Downgrading browser extensions is extremely painful, you are totally right about it (especially in Firefox, surprisingly!). I'm glad you got it sorted. The latest native host was released half a year ago, so hopefully has been battle tested enough not to cause issues on your production system. Enjoy the app 👍
