### ISSUE TITLE
Mac Brew Install Path

### ISSUE THREAD

**Issue by dactylroot** [browserpass/browserpass-native#140]
### General information
 
-   MacOS Version Ventura 13.6.1:
-   Browser: Firefox v120.0.1
-   Information about the host app:
    -   Installed via HomeBrew
    -   version: 3.0.8 to 3.1.0
-   Information about the browser extension:
    -   Installed via firefox webstore
    -   version: 3.8.0, updated 2023 October 30

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

The [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section is my issue. I only have a warning about updating my host app, but the host app seems to be in the wrong folder. Homebrew seems to be installing to the original version directory **/usr/local/Cellar/browserpass/3.0.8** instead of **/usr/local/Cellar/browserpass/3.1.0**

---

### Exact steps to reproduce the problem

1. Install version 3.0.8 via homebrew `brew install browserpass@3.0.8`

2. Update to a later version `brew update; brew upgrade browserpass`

3. Examine configuration with `brew doctor; ls /usr/local/cellar/browserpass`

### What should happen?
Newer version of browserpass source should be installed to **/usr/local/Cellar/browserpass/3.1.0**.

### What happened instead?

        $ brew info browserpass
        ==> amar1729/formulae/browserpass: stable 3.1.0 (bottled)
        Host application for browser extension providing access to your password store
        https://github.com/browserpass/browserpass-native
        /usr/local/Cellar/browserpass/3.0.8 (11 files, 3.6MB) *
          Poured from bottle on 2022-09-07 at 12:48:09
        From: https://github.com/amar1729/homebrew-formulae/blob/HEAD/Formula/browserpass.rb
        ==> Dependencies
        Build: coreutils ✔, gnu-sed ✔, go ✘
        Required: gpg ✔, pinentry ✔, pinentry-mac ✔
        ==> Caveats
        ********************************************************************************
        * To configure your browser, RUN THE FOLLOWING:
        
        $ PREFIX='/usr/local/Cellar/browserpass/3.1.0' make hosts-BROWSER-user -f '/usr/local/Cellar/browserpass/3.1.0/lib/browserpass/Makefile'
        
        * Where BROWSER is one of the following: [chromium chrome vivaldi brave firefox]
        ********************************************************************************
        $ ls /usr/local/Cellar/browserpass/
        3.0.8

**Comment by maximbaz** [comment]
Hello! The homebrew formula is not managed by us, could I please ask you to report it on https://github.com/Amar1729/homebrew-formulae? :pray: 

I also saw there exists https://github.com/Amar1729/homebrew-formulae/issues/28, but on the first glance it doesn't seem to be related...

**Comment by dactylroot** [comment]
> Hello! The homebrew formula is not managed by us, could I please ask you to report it on https://github.com/Amar1729/homebrew-formulae? 🙏
> 
> I also saw there exists [Amar1729/homebrew-formulae#28](https://github.com/Amar1729/homebrew-formulae/issues/28), but on the first glance it doesn't seem to be related... (ooor maybe this comment is onto something similar? [Amar1729/homebrew-formulae#28 (comment)](https://github.com/Amar1729/homebrew-formulae/issues/28#issuecomment-1841040043))

I think you're right and these look related to me. I will continue there.
