### ISSUE TITLE
fedora copr

### ISSUE THREAD

**Issue by prez** [browserpass/browserpass-native#142]
https://copr.fedorainfracloud.org/coprs/maximbaz/browserpass/

Is this an officially supported installation method?

https://download.copr.fedorainfracloud.org/results/maximbaz/browserpass/pubkey.gpg does not seem to match https://maximbaz.com/pgp_keys.asc (disclaimer: I don't really have a clue about proper gpg use)...

**Comment by maximbaz** [comment]
I can confirm that it was indeed created by me, I made it because right now I use fedora, and yes it installs browserpass according to the official documentation. I haven't fully decided yet if I'm going to add it to this repo as the official recommended way yet, but very likely that I will.

**Comment by maximbaz** [comment]
Oh big thanks for the catch! It shows I use firefox in daily usage :sweat_smile: :see_no_evil: Pushed the fix now, hopefully.

**Comment by maximbaz** [comment]
Hey! I ended up not using Fedora in the end, so I dont think I'll be maintaining that copr - however would you like to take over that copr? (or maybe rather create one in your name). In which case I'm happy to share the spec file!

**Comment by maximbaz** [comment]
As for the brave browser,  to make it work you can either follow the README to execute the `make hosts-brave-user`, or extend the fedora copr with support for brave by implementing this part there: https://github.com/browserpass/browserpass-native/blob/c4c71108293b259bf592ec5d9a7f13559a5f8fca/Makefile#L354
