### ISSUE TITLE
Updating OS packages for v3

### ISSUE THREAD

**Issue by maximbaz** [browserpass/browserpass-native#31]
There will be a new major release of Browserpass soon, so I want to ping OS package maintainers to give you time to prepare for the release.

I've created a Makefile, so the build & packaging should be really simple now. For Arch Linux, all I do now is:

```
make configure
make browserpass
make test
make install
```

For reference: [PKGBUILD](https://github.com/maximbaz/pkgbuilds/blob/master/browserpass/PKGBUILD)

To configure browsers, Makefile is also being installed to `/usr/lib/browserpass/`, so if you guys implemented some wrappers (like I know @dustinwilson implemented `browserpass-setup`), that shouldn't be necessary anymore - users can just do:

```
cd /usr/lib/browserpass
make hosts-chromium-user
```

For full reference, see [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers)

For Nix / NixOS, a special request if someone could review this section of the documentation, I ported it from the old Browserpass repo but I'm not entirely sure it's correct: https://github.com/browserpass/browserpass-native#install-on-nix--nixos

ping @meskes, @dustinwilson, @Infinisil, @fpletz, @dermetfan, @pajowu

Completed distro packages:
  - [x] Arch Linux
  - [x] NixOS
  - [x] macOS (homebrew tap)
  - [x] Gentoo Linux
  - [ ] Ubuntu
  - [x] Debian

**Comment by Infinisil** [comment]
The Makefile currently assumes that browserpass is installed in /usr/lib. Can you make this configurable with a variable? The user won't be able to change the Makefile easily on Nix/NixOS, so we'd have to patch it.

**Comment by maximbaz** [comment]
Yes we can do anything you need 👍 The `install` target is respecting `DESTDIR` variable, I needed that for Arch Linux package, are you referring that all those `hosts-*` and `policies-*` targets must also respect this variable, or what do you have in mind?

**Comment by Infinisil** [comment]
@maximbaz Something like that yes, specifically in these places it assumes browserpass was installed /usr/lib: https://github.com/browserpass/browserpass-native/blob/8411954b5a38ed7ed78aad2036e0bebdebfa982f/Makefile#L100

In addition, I think it's common to allow configuration through both `DESTDIR` and `PREFIX`, `DESTDIR` being empty by default, and `PREFIX` being something like `/usr` or `/usr/local`. In Nix specifically, we'll set `PREFIX` to be empty.

**Comment by maximbaz** [comment]
@Infinisil may I ask you for a review in #32?

**Comment by maximbaz** [comment]
I will release v3 to webstores on Saturday, April 13th; would be really awesome if you guys get ready for this date as browser extension is not backwards compatible and will not work after auto-update with the old native host.

**Comment by Infinisil** [comment]
Is the new native host compatible with the old browser extension?

**Comment by maximbaz** [comment]
No, the communication protocol has changed completely, and it was too much work to make them compatible, therefore the bump in major version.

**Comment by Infinisil** [comment]
Huh, but that makes it nearly impossible to not break anything at some point. The only way it won't break is if the user gets the native host update exactly at the same time as when the browser extension auto-updates. And because the native host isn't in any way tied to the browser extension, but provided by the package managers/installed manually, this inevitably leads to a version mismatch.

The only way I can see this working is if you rename the binary to `browserpass3`, then the old browser extension can use `browserpass` as its binary, and the new one can use `browserpass3`. As a package maintainer I can then provide both versions in the same package for a while. Some time before the browser extension release, so the native host update can go through all the build pipelines for package managers and gotten via a system upgrade, and some time after the release, so people who didn't get the browser extension update yet (if you don't restart your browser for days at a time like me) can still use the old native host.

**Comment by maximbaz** [comment]
The binary name is configurable with `BIN` variable in Makefile, so you as a package maintainer are free to name the binary how ever you want. I don't plan for a non-breaking update, it was a conscious decision given the amount of time I have, I only want to decrease the time things are in a broken state - therefore an early ping for you guys 🙂 

By the way, I believe it isn't required to restart browser to receive auto-update, at least not in Chromium.

I'm also planning to push a new version of v2 to web stores a week before v3 release, which will show a notification about the upcoming breaking update, and that folks need to plan for a time to update native host app to make the extension work properly again.

**Comment by Infinisil** [comment]
Ohh right, the browser extension uses `com.github.browserpass.native.json` to determine which binary to use, which can coexist with `com.dannyvankooten.browserpass.json`, yeah that works then, I can make it install both of those.

**Comment by meskes** [comment]
On Sun, 2019-03-31 at 03:24 -0700, Maxim Baz wrote:
> I will release v3 to webstores on Saturday, April 13th; would be
> really awesome if you guys get ready for this date as browser
> extension is not backwards compatible and will not work after auto-
> update with the old native host.

I have to admit that I completely missed the new development, thanks
for the heads up. I'm not sure yet, whether I really want to have two
packages or combine both to one. Is there a particular reason why you
did that Maxim?

Two more issues, Debian does not have a full browserify but only
browserify-lite which nicely compile all js files, but none actually
works. No idea why, maybe somebody else has one. It surely is a fact
that might be worth keeping in mind, just in case.

Second, in my test runs I found that browserpass does *not* fill in the
login information in our company OpenXchange server anymore, but only
in chromium, firefox works nicely. This is not related to version 3,
2.0.22 shows the same symptom. Any idea how to debug?

Michael
-- 
Michael Meskes
Michael at Fam-Meskes dot De, Michael at Meskes dot (De|Com|Net|Org)
Meskes at (Debian|Postgresql) dot Org
Jabber: michael at xmpp dot meskes dot org
VfL Borussia! Força Barça! SF 49ers! Use Debian GNU/Linux, PostgreSQL

**Comment by maximbaz** [comment]
> I'm not sure yet, whether I really want to have two packages or combine both to one. Is there a particular reason why you did that Maxim?

Sorry I think I lost context, what are you asking about exactly? 🙂 Why is v3 incompatible with v2? It was rewritten from scratch, and it was a great opportunity to redesign the communication protocol and the native host in general. Or why we now have split repos for native app and browser extension? This is because in practice these are different projects, with different codebase, when it was a single project it didn't make sense for users for example to update their native host if only browser extension changed. I think distro packages should only provide native host app, and leave installing extension to the user. Or do you have some particular reasons to provide browser extension as well via a OS package, and if so, how do users install it in the browser?

Assuming that you don't need to handle browser extension part in the distro package at all, you don't need to worry about browserify anymore 🙂 

For the issues where Browserpass is not able to fill login form, please post the link here and I'll investigate: https://github.com/browserpass/browserpass-extension/issues/62

**Comment by meskes** [comment]
On Tue, 2019-04-02 at 12:58 +0000, Maxim Baz wrote:
> native host if only browser extension changed. I think distro
> packages should only provide native host app, and leave installing
> extension to the user. Or do you have some particular reasons to
> provide browser extension as well via a OS package, and if so, how do
> users install it in the browser?

That was actually the question. I see the reason for your splitting up
the two, but I don't really think having both as separate packages
makes sense. In Debian if you install the one browserpass package, you
have a working extension for chromium and firefox.

Users don't have to install it. As soon as the package is installed the
extension is enabled in each browser automatically.

> Assuming that you don't need to handle browser extension part in the
> distro package at all, you don't need to worry about browserify
> anymore 🙂

Yeah, that would be an advantage, but unfortunately it is not. :)

> For the issues where Browserpass is not able to fill login form,
> please post the link here and I'll investigate:
> browserpass/browserpass-extension#62

Will do as soon as I find the time.

Thanks.

Michael
-- 
Michael Meskes
Michael at Fam-Meskes dot De, Michael at Meskes dot (De|Com|Net|Org)
Meskes at (Debian|Postgresql) dot Org
Jabber: michael at xmpp dot meskes dot org
VfL Borussia! Força Barça! SF 49ers! Use Debian GNU/Linux, PostgreSQL

**Comment by maximbaz** [comment]
> Users don't have to install it. As soon as the package is installed the extension is enabled in each browser automatically.

I'm really curious how you achieved that! For Chromium-based browsers there's something called "policy", which can force browser to install an extension from Web store (not from local file as far as I know), but I'm not aware of any such possibility for Firefox...

**Comment by maximbaz** [comment]
I tracked this down to https://wiki.debian.org/onlyjob/WebExtensions%20packaging, astonishing! I will do the same for Arch Linux 🙂 

Nevertheless, I think it's still reasonable to split the packages, let "browserpass" provide only native host and create two new packages "browserpass-chromium" and "browserpass-firefox", which would be based on "chromium.zip" and "firefox.zip" from `browserpass-extension` releases respectfully. Not only we will have cleaner separation, but also users aren't forced to e.g. install Chromium extension if they only use Firefox.

@Infinisil make sure to check this out as well, not only it is cool because you will provide users with an extension that is built from sources that are verified with PGP signature instead of trusting whatever is on webstore, but also you will be in complete control of when their extension upgrades.

**Comment by meskes** [comment]
> Nevertheless, I think it's still reasonable to split the packages,
> let "browserpass" provide only native host and create two new
> packages "browserpass-chromium" and "browserpass-firefox", which
> would be based on "chromium.zip" and "firefox.zip" from browserpass-
> extension releases respectfully. Not only we will have cleaner
> separation, but also users aren't forced to e.g. install Chromium
> extension if they only use Firefox.

But there is only one extension in the package. The new webextension
works with both browser without any issue. The same code works for both
browser, so there is no need to have this separation.

Michael
-- 
Michael Meskes
Michael at Fam-Meskes dot De, Michael at Meskes dot (De|Com|Net|Org)
Meskes at (Debian|Postgresql) dot Org
Jabber: michael at xmpp dot meskes dot org
VfL Borussia! Força Barça! SF 49ers! Use Debian GNU/Linux, PostgreSQL

**Comment by maximbaz** [comment]
Based on the docs I found I understood you will still create for example symlinks in `/usr/share/chromium/extensions/` folder even if a user doesn't really use Chromium; but of course it's up to you how you want to package, you can create a combined `browserpass-webextension`, or even create a single `browserpass` package as you have now, which would be based on several source archives :wink: 

I must also say you are lucky, I couldn't convince Chromium's maintainer on Arch to support loading unpacked extensions from `/usr/share/chromium/extensions/*` folders; I had to use https://github.com/browserpass/browserpass-extension/pull/68, which means on Arch Linux packages `browserpass-chromium` and `browserpass-firefox` would be completely different, one based on unpacked zip archive, another based on packed `crx` file.

**Comment by maximbaz** [comment]
By the way, when packaging remember that the extensions are not exactly identical: manifests are slightly different for Chromium and Firefox.

**Comment by maximbaz** [comment]
My preliminary packages for Arch Linux, in case anyone needs for reference: [browserpass-chromium](https://github.com/maximbaz/pkgbuilds/blob/master/browserpass-chromium/PKGBUILD) and [browserpass-firefox](https://github.com/maximbaz/pkgbuilds/blob/master/browserpass-firefox/PKGBUILD)

**Comment by stefanct** [comment]
As of now the firefox extension has been auto-updated in Debian (stable) and leaves the user with `Error: Error: Attempt to postMessage on disconnected port` when clicking on the new browserpass icon. Does building from source work or would that run in the same problems you saw, @meskes?

**Comment by maximbaz** [comment]
Building from sources (or using pre-built archives from Github releases) should work @stefanct, especially if you already have the extension and only need the native host part, give it a try and ping me if you need help 👍

**Comment by meskes** [comment]
@stefanct with auto-update you mean from the extension store right? There is no Debian package for browserpass in Debian stable. Did you use a precompiled native host binary or did you build that yourself? The issues I ran into were solely with the browserified javascript and were solved by the precompiled files. I still have some buildsystem issues, which is why there are no new packages for unstable yet.

**Comment by stefanct** [comment]
@meskes Yes, I was referring to the browser-part. I have apparently installed the `webext-browserpass` package version 2.0.22-1 from testing/unstable (but FF is from stable security). Sorry for the confusion. I have not tried (and would like to avoid) building it myself (too much other stuff on the plate ;) unless you struggle with something specifically where I could help (I am not a debian dev though).

**Comment by meskes** [comment]
On Tue, 2019-04-16 at 17:40 +0000, Stefan Tauner wrote:
> @meskes Yes, I was referring to the browser-part. I have apparently
> installed the webext-browserpass package version 2.0.22-1 from
> testing/unstable (but FF is from stable security). Sorry for the 

And it is with this version you have a problem? Or the v3 one this
issue is about?

Did you manually grab the webext-browserpass deb file and install it on
your stable system? I just tried that and it works flawlessly on my
system.

Michael
-- 
Michael Meskes
Michael at Fam-Meskes dot De, Michael at Meskes dot (De|Com|Net|Org)
Meskes at (Debian|Postgresql) dot Org
Jabber: michael at xmpp dot meskes dot org
VfL Borussia! Força Barça! SF 49ers! Use Debian GNU/Linux, PostgreSQL

**Comment by stefanct** [comment]
On Wed, 17 Apr 2019 03:21:14 -0700
meskes <notifications@github.com> wrote:

> On Tue, 2019-04-16 at 17:40 +0000, Stefan Tauner wrote:
> > @meskes Yes, I was referring to the browser-part. I have apparently
> > installed the webext-browserpass package version 2.0.22-1 from
> > testing/unstable (but FF is from stable security). Sorry for the
>
> And it is with this version you have a problem? Or the v3 one this
> issue is about?

I was under the impression that this issues is about the necessity to
update the native application when the browser extension is updated to
v3 (which happens/happened automatically). I did not try to upgrade the
native app yet.

> Did you manually grab the webext-browserpass deb file and install it on
> your stable system? I just tried that and it works flawlessly on my
> system.

I can't remember for sure - it's been a while, but I guess I just
installed it normally via apt (I can force fetching from testing and
unstable due to apt-pinning). My initial post here was only meant to a)
document the error message for search engines to pick up, and b) to
ensure that trying to build the native app on debian as a workaround is
not futile.

**Comment by maximbaz** [comment]
Every distro has updated the package, except Ubuntu, but that should propagate automatically from Debian. Thanks everyone, closing this now!
