### ISSUE TITLE
path not set

### ISSUE THREAD

**Issue by 532910** [browserpass/browserpass-native#35]
path in the ```~/.mozilla/native-messaging-hosts/com.github.browserpass.native.json``` wasn't replaced after

```
% wget https://github.com/browserpass/browserpass-native/releases/download/3.0.1/browserpass-linux64.zip
% unzip browserpass-linux64.zip
% cp browserpass-linux64 browserpass
% DESTDIR=/home/sergio/.local PREFIX= make install
% DESTDIR=/home/sergio/.local PREFIX= make hosts-firefox-user
```

And I need to correct it manually.

**Comment by maximbaz** [comment]
You have missed one of the installation steps in README (I just added it recently, so maybe it happened after you tried), could you please try again?

"Configure the hosts json files **using `make configure`** and then install the app ..."

I'll try to make it more obvious in the README, thanks again ;)

**Comment by 532910** [comment]
Sorry. I though the "configure" step is for compiling.

**Comment by maximbaz** [comment]
Got it, okay then I know what exactly needs clarifying, thanks :)

**Comment by 532910** [comment]
It's clear now, thank you!
