### ISSUE TITLE
Error: Specified native messaging host not found.

### ISSUE THREAD

**Issue by haslinger** [browserpass/browserpass-native#41]
After updating on Ubuntu Linux 16.04 client and native, I get
`Error: Specified native messaging host not found.` 
on while on the command line

```
browserpass-linux64 -v
DEBU[2019-04-08T13:46:59+02:00] Starting browserpass host app v3.0.4 
```
would start without any errors.

On Firefox, the error message is: `Error: Attempt to postMessage on disconnected port`
Any ideas, which problem I'm facing?

**Comment by maximbaz** [comment]
You probably haven't executed the [Configuring browsers](https://github.com/browserpass/browserpass-native#configure-browsers) section, have a look and let me know if you face any issues there 🙂

**Comment by haslinger** [comment]
Thanks for the quick response!
I had executed it, for Chrome, as for Firefox as well. 
No issues calling them, they returned
```
stefan@indigo:~/Programme/browserpass-linux64-3.0.4$ sudo make hosts-chrome
'/etc/opt/chrome/native-messaging-hosts/com.github.browserpass.native.json' -> '/usr/lib/browserpass/hosts/chromium/com.github.browserpass.native.json'
stefan@indigo:~/Programme/browserpass-linux64-3.0.4$ sudo make hosts-firefox
'/usr/lib/mozilla/native-messaging-hosts/com.github.browserpass.native.json' -> '/usr/lib/browserpass/hosts/firefox/com.github.browserpass.native.json'
```

**Comment by maximbaz** [comment]
Let's double check that the files contain correct paths to the `browserpass` binary, run this:

```
cat /etc/opt/chrome/native-messaging-hosts/com.github.browserpass.native.json
cat /usr/lib/mozilla/native-messaging-hosts/com.github.browserpass.native.json
```

Both of them inside must contain a valid full path to the browserpass (it was set to via `make configure` step).

Can you confirm that the paths are correct?

**Comment by haslinger** [comment]
There's the issue, they contain /usr/bin/browserpass-XXXX.
I'll start from the beginning ...

**Comment by maximbaz** [comment]
If you can think of a way for me to improve instructions in README or make them more clear, or if you can tell me what was less obvious, please let me know! And thanks for trying out the update!

**Comment by haslinger** [comment]
My issue was, that I first started it with 
```
make BIN=browserpass-XXXX configure
```
and running it a second time with
```
make BIN=browserpass-linux64 configure
```
didn't override the configs.
Overriding manually didn't help as well. 
I guess I'll have to dig a little deeper to get rid of all the artifacts with XXXX

**Comment by maximbaz** [comment]
It's just these two files that you now have to manually edit, nothing else is impacted.

**Comment by maximbaz** [comment]
https://github.com/browserpass/browserpass-native/commit/98ef042db14c6d3d7bfe3d1da0d7022db4fa971d

**Comment by haslinger** [comment]
Paths are now consistent:
```
stefan@indigo:~$ !1994
cat /etc/opt/chrome/native-messaging-hosts/com.github.browserpass.native.json
{
    "name": "com.github.browserpass.native",
    "description": "Browserpass native component for the Chromium extension",
    "path": "/usr/bin/browserpass-linux64",
    "type": "stdio",
    "allowed_origins": [
        "chrome-extension://naepdomgkenhinolocfifgehidddafch/",
        "chrome-extension://pjmbgaakjkbhpopmakjoedenlfdmcdgm/",
        "chrome-extension://klfoddkbhleoaabpmiigbmpbjfljimgb/"
    ]
}
stefan@indigo:~$ /usr/bin/browserpass-linux64 -v
DEBU[2019-04-08T14:16:19+02:00] Starting browserpass host app v3.0.4         
^C
```
Browser restarted, same error `Error: Specified native messaging host not found.`.
Hmmm.

**Comment by maximbaz** [comment]
And are you sure you are trying to use the new browser extension, does it have the new logo in form of a key? Both extension and native host app have to be updated, but the new extension will only be pushed to web stores on Saturday.

**Comment by haslinger** [comment]
That's it. I didn't realize that the extension that comes from the webstore right now is not compatible to the latest native.
So the only suggestion would be to warn with something like: Don't update native before Saturday ;-)
Thanks for all your time and effort!

**Comment by maximbaz** [comment]
I was trying to reflect this in [FAQ](https://github.com/browserpass/browserpass#faq), but since it will be a breaking change, maybe it is actually better to let people update some time this week and until extension in web store gets auto-updated, manually download it from Github release and load in the browser. This way on Saturday things will begin to "just work" instead of Browserpass suddenly breaking on Saturday 😉

**Comment by gncs** [comment]
I just ran into the exact same problem. That the links provided in the documentation are still pointing to the old versions is very confusing. Please update the README accordingly, thank you!

**Comment by maximbaz** [comment]
@gncs sorry I think I lost context here, which links are you referring to?

**Comment by gncs** [comment]
In the README it says:
```
Install the extension from [Firefox Add-ons](https://addons.mozilla.org/en-US/firefox/addon/browserpass-ce/) (which will provide auto-updates)
```
If you follow this link, you are directed to the old version of the Firefox extension (2.x) and not (3.x).

**Comment by maximbaz** [comment]
Oh, I see. Sorry for the confusion, yes we are planning the release on Saturday, so since Saturday it will be correct!

**Comment by gncs** [comment]
Yes, but until then new users will not be able to get this extension to work. The old repository is marked as archived so they assume this to work...

**Comment by maximbaz** [comment]
Fair point, updated: https://github.com/browserpass/browserpass-extension/commit/dd4b4ff6d1f3f7e5419529a38c4e09db0baf590d
