### ISSUE TITLE
Error: Error: "Invalid action"

### ISSUE THREAD

**Issue by alorimer** [browserpass/browserpass-native#42]
I am on Arch Linux. Today I updated the native server with `yay -Syu browserpass`. I then set up `sudo make hosts-chromium`. I then removed the old Chromium extension, and installed the new one from the downloaded crx. All this completed without errors.

Now when I open the new extension, it says Error: Error: "Invalid action". It's definitely the new extension with the key, and `browserpass -v ` reports 2.0.21.

Any ideas? Possibly some bug in the pre-release setup, idk. I thought I followed everything exactly so it's probably worth sorting this out before public release.

**Comment by alorimer** [comment]
Umm, I just realised I should be on native version 3.0.4 not 2.0.21... my bad. Perhaps there should be a warning in the extension about mismatching versions?

**Comment by maximbaz** [comment]
I was trying to reflect this in [FAQ](https://github.com/browserpass/browserpass#faq), that versions are incompatible.

By the way, if you want to try 3.0.4, you can also download "browserpass-*" packages from my repo 😉 If you for example install "browserpass" and "browserpass-chromium", you won't need to do any manual installation steps like running "make" 😉 

https://pkgbuild.com/~maximbaz/repo/
