### ISSUE TITLE
Error: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by jimerickson** [browserpass/browserpass-native#50]
installed as per the instructions for google-chrome on ubuntu 18.04.2 on 64-bit system. but when i click on the extension in chrome  get Error: SyntaxError: Unexpected end of JSON input. really enjoy the work you do. hope someone can help with this.

**Comment by erayd** [comment]
Could you please provide:
- Your browser type
- Your browser version
- The native host version installed on your system
- The extension version as reported by your browser
- how and where from you installed the native host
- how and where from you installed the extension

**Comment by jimerickson** [comment]
browser version = Version 73.0.3683.103 (Official Build) (64-bit)
native host version = Browserpass host app version: 3.0.0 
extension version reported in browser = 3.0.10
native host installed from github via :
make
make configure
sudo make install
sudo make hosts-chrome
the extension was installed via chrome update.

thanks for the quick reply!

**Comment by maximbaz** [comment]
This is very interesting, first of all consider installing 3.0.6 of the native app (your extension will complain about outdated host app anyway, once we make it work), but then please download [this file](https://github.com/browserpass/browserpass-native/files/3077875/request.hex.txt), run the command below and shows us output:


```
$ browserpass < /path/to/request.hex.txt
```

Please also confirm if you have a file `.browserpass.json` in the root of your password store directory (if you do, does it contain a valid json?).

**Comment by jimerickson** [comment]
ok so it does work with 3.0.6 yay!
$  browserpass < ~/Downloads/request.hex.txt
�{"status":"ok","version":3000000,"data":{"defaultStore":{"path":"/home/jim/.password-store","settings":""},"storeSettings":{}}}
also there is no .browserpass.json in ~/.password-store.

**Comment by maximbaz** [comment]
> ok so it does work with 3.0.6 yay!

Just to confirm, did you fix the issue, browser extension also works now for you after you upgraded to 3.0.6?

**Comment by jimerickson** [comment]
yes that is correct! thanks!

**Comment by maximbaz** [comment]
Enjoy your new extension then! 🙂
