### ISSUE TITLE
archlinux: unable to install browserpass

### ISSUE THREAD

**Issue by vikasrawal** [browserpass/browserpass-native#58]
### General information

-   Operating system + version: Arch Linux
-   Browser + version: Firefox 66.0.3
-   Information about the host app:
    -   How did you install it?
        
AUR version
    -   If installed an official release, put a version (`$ browserpass --version`):
    -   If built from sources, put a commit id (`$ git describe --always`):
-   Information about the browser extension:
    -   How did you install it?
        
yay -S browserpass

    -   Browserpass extension version as reported by your browser:
3.0.12
---

If you are seeing "Error: Specified native messaging host not found", have you followed [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

---

### Exact steps to reproduce the problem

1. yay -S browserpass

(I had browserpass installed on this system. Removed it, and am trying to install again).

### What should happen?

Should install. Compilation goes fine.

### What happened instead?

Gives me this error:

cmd/browserpass/main.go:10:2: cannot find package "github.com/dannyvankooten/browserpass" in any of:
	/usr/lib/go/src/github.com/dannyvankooten/browserpass (from $GOROOT)
	/home/vikas/go/src/github.com/dannyvankooten/browserpass (from $GOPATH)
cmd/browserpass/main.go:11:2: cannot find package "github.com/dannyvankooten/browserpass/protector" in any of:
	/usr/lib/go/src/github.com/dannyvankooten/browserpass/protector (from $GOROOT)
	/home/vikas/go/src/github.com/dannyvankooten/browserpass/protector (from $GOPATH)
==> ERROR: A failure occurred in build().
    Aborting...
Error making: browserpass-git

**Comment by erayd** [comment]
You are trying to install an outdated version. The URL referenced in the error refers to a previous location for the v2 repository. Have you run `pacman -S` recently?

Your error refers to lines 10 & 11 of main.go, which in v3 contain [something else entirely](https://github.com/browserpass/browserpass-native/blob/master/main.go#L10).

**Comment by maximbaz** [comment]
indeed, make sure to install this one: 

https://www.archlinux.org/packages/community/x86_64/browserpass/

if you are on Manjaro or some other distro that blocks official Arch repos, you can install it like this until the repos are synchronized

pacman -U https://www.archlinux.org/packages/community/x86_64/browserpass/download/

**Comment by vikasrawal** [comment]
Thanks. Worked.
