### ISSUE TITLE
Error: the symlink points to a non-existent location

### ISSUE THREAD

**Issue by kabads** [browserpass/browserpass-native#63]
### General information

-   Operating system + version: Mac OS 10.14.3
-   Browser + version:  Firefox 66.0.3
-   Information about the host app: 
    -   How did you install it?
        By brew install 
    -   If installed an official release, put a version (`$ browserpass --version`): 
       Browserpass host app version: 3.0.6
    -   If built from sources, put a commit id (`$ git describe --always`):
-   Information about the browser extension:
    -   How did you install it?
       Installed from firefox addon repository 
    -   Browserpass extension version as reported by your browser:

---

If you are seeing "Error: Specified native messaging host not found", have you followed [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

^ This is the part where the install fails. On Mac OS, I'm getting 

    sudo make hosts-firefox
    /Library/Application Support/Mozilla/NativeMessagingHosts/com.github.browserpass.native.json    -> /usr/lib/browserpass/hosts/firefox/com.github.browserpass.native.json
    Error: the symlink points to a non-existent location
---

### Exact steps to reproduce the problem

1. Follow documentation to install from binary 

2. Go to /usr/local/lib/browserpass

3. Run sudo make hosts-firefox

### What should happen?
Install fine.
### What happened instead?
Error: the symlink points to a non-existent location

**Comment by kabads** [comment]
Copying over the file manually resolves this (i.e. it seems that the install script is broken on Mac).

**Comment by maximbaz** [comment]
I'm glad you solved it @kabads!

The reason `sudo make hosts-firefox` didn't work is because you must provide the same `PREFIX` as `brew install` is using internally.

`brew install` actually [prints out the full command](https://github.com/Amar1729/homebrew-formulae/blob/bc3b0559e31a092c39bae7affa588b0c71efa808/browserpass.rb#L39-L54) that you need to run to configure browsers, I think you just didn't notice it.

@Amar1729 consider perhaps shortening the text, and highlighting it with a wall of asterisks. I'd recommend something like this:

    <<~EOF
      ********************************************************************************************************************
      * To configure your browser, RUN THE FOLLOWING:

      $ PREFIX='/usr/local/opt/browserpass' make hosts-BROWSER-user -f /usr/local/opt/browserpass/lib/browserpass/Makefile

      * Where BROWSER is one of the following: [chromium chrome vivaldi brave firefox]
      ********************************************************************************************************************
    EOF
