### ISSUE TITLE
Support new browser: Waterfox

### ISSUE THREAD

**Issue by mattconnell** [browserpass/browserpass-native#69]
### General information

-   Operating system + version: Gentoo Linux
-   Browser + version: Waterfox 56.2.8
-   Information about the host app:
    -   How did you install it?  Via package manager
    -   If installed an official release, put a version Browserpass host app version: 3.0.6
-   Information about the browser extension:
    -   How did you install it? Via AMO (https://addons.mozilla.org/en-US/firefox/addon/browserpass-ce/?src=search)
    -   Browserpass extension version as reported by your browser: 3.1.1

---

Browser extension displays:

`Error: Could not establish connection. Receiving end does not exist.`

There is no Waterfox-specific instruction set.  I had hoped that it would "just work", since WF is a FF derivative, but I am unsure how to troubleshoot this.

**Comment by maximbaz** [comment]
To clarify, does Browserpass work for you in Firefox, but not in Waterfox?

If so, this means Waterfox uses a different location to store native host configuration. If you are interested investigating this, a PR would be welcome 🙂 

You would need to duplicate [this section of Makefile](https://github.com/browserpass/browserpass-native/blob/fe361b1f95e64c4001ebeb4a5018fd3fad38333b/Makefile#L222-L248) and put there proper paths for Waterfox browser.

**Comment by maximbaz** [comment]
Closing due to the lack of interest, but if anyone wants to contribute, please feel free to submit a PR!
