### ISSUE TITLE
Error with firefox extension : Error: Attempt to postMessage on disconnected port

### ISSUE THREAD

**Issue by EmrysMyrddin** [browserpass/browserpass-native#73]
### General information

-   Operating system + version: macOS 10.14.4 (18E226)
-   Browser + version: Firefox 67.0
-   Information about the host app:
    -   How did you install it? `brew install amar1729/formulae/browserpass`
    -   If installed an official release, put a version (`$ browserpass --version`): 3.0.6
    -   If built from sources, put a commit id (`$ git describe --always`):
-   Information about the browser extension:
    -   How did you install it? via the Firefox Add-ons web site
    -   Browserpass extension version as reported by your browser: 3.1.1

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section? Yes

---

### Exact steps to reproduce the problem

1. Install the native app with brew

2. Install firefox Extension

3. Click on browserpass icon

### What should happen?

Open a popup with an input to search for login

### What happened instead?

Open a popup with the error message : `Error: Attempt to postMessage on disconnected port`

### Solution

I had to manualy run `PREFIX=/usr/local make hosts-firefox` to make it work.
It seems that brew doesn't install browserpass in its default location which break simlinks.

Strangely, the chrome extension works without any manual step.

**Comment by maximbaz** [comment]
Hey, I think you should open an issue at [homebrew-formulae](https://github.com/Amar1729/homebrew-formulae/), if [their suggested command](https://github.com/Amar1729/homebrew-formulae/blob/76f6b20e5178ecf24fa157b1bd7922551e6e0129/browserpass.rb#L41-L45) to configure browsers didn't work for you.

But in any case, glad that you made it work, enjoy 🙂
