### ISSUE TITLE
Native messaging host not found

### ISSUE THREAD

**Issue by bkabbott** [browserpass/browserpass-native#75]
### General information

-   Operating system + version:
-   Browser + version:
-   Information about the host app:
    -   How did you install it?
        
    -   If installed an official release, put a version (`$ browserpass --version`):
    -   If built from sources, put a commit id (`$ git describe --always`):
-   Information about the browser extension:
    -   How did you install it?
        
    -   Browserpass extension version as reported by your browser:

---

I am running Ubuntu 18.04. I installed the app by downloading browserpasslinux64.zip. Then I unzipped the files and ran ./install. 

I later ran the make command and it said make: Nothing to be done for 'browserpass-linux64'.

The browserpass extension is 3.11.

---

### Exact steps to reproduce the problem

I installed the browserpass extension then I installed the Linux program.

### What happened instead?

Error: Error: Specified native messaging host not found

**Comment by maximbaz** [comment]
Hey, I think you are looking for this section of the documentation: https://github.com/browserpass/browserpass-native/blob/master/README.md#install-manually

let me know if you still have some questions.

**Comment by bkabbott** [comment]
Thank you for responding. I might need to call it a day I've been at it a while but I believe I have installed it successfully.

I received this message

Installing Chrome host config
Native messaging host for Chrome has been installed to /home/brian/.config/google-chrome/NativeMessagingHosts.

**Comment by bkabbott** [comment]
I should add I installed the dependencies and the webext-browserpass package.
https://packages.ubuntu.com/source/bionic/browserpass

Thank you for helping me.

**Comment by maximbaz** [comment]
That package is outdated (it contains version 2, not 3), so I don't recommend using it. You better uninstall it and follow the steps to install browserpass manually. You can tell if you have the right version by comparing the UI of the extension popup, it has dark theme in v3 :)

**Comment by bkabbott** [comment]
I removed the package. Here are the steps I took:
Here are the steps I took:
1. Downloaded browserpass-linux64-3.0.6
2. Ran make BIN=browserpass-linux64 configure 
/bin/sed -i 's|"path": ".*"|"path": "'"/usr/bin/browserpass-linux64"'"|' browser-files/chromium-host.json
/bin/sed -i 's|"path": ".*"|"path": "'"/usr/bin/browserpass-linux64"'"|' browser-files/firefox-host.json
3. sudo make BIN=browserpass-linux64 install
/usr/bin/install -Dm755 -t "/usr/bin/" browserpass-linux64
/usr/bin/install -Dm644 -t "/usr/lib/browserpass/" Makefile
/usr/bin/install -Dm644 -t "/usr/share/licenses/browserpass/" LICENSE
/usr/bin/install -Dm644 -t "/usr/share/doc/browserpass/" README.md
/usr/bin/install -Dm644 browser-files/chromium-host.json   "/usr/lib/browserpass/hosts/chromium/com.github.browserpass.native.json"
/usr/bin/install -Dm644 browser-files/chromium-policy.json "/usr/lib/browserpass/policies/chromium/com.github.browserpass.native.json"
/usr/bin/install -Dm644 browser-files/firefox-host.json    "/usr/lib/browserpass/hosts/firefox/com.github.browserpass.native.json"

-----
I installed all of the extensions listed on the link above. I'm still getting the Specified native messaging host not found error.

**Comment by maximbaz** [comment]
@bkabbott hey, sorry this ticket has completely slipped my attention, is it still an issue or have you been able to resolve the issue?

**Comment by bkabbott** [comment]
I haven't been able to get it working on Ubuntu 18.04. I'm happy using the terminal however so I will close this ticket.

**Comment by vlazic** [comment]
I had the same problem.
Solution is to install the chormium from here: https://launchpad.net/~chromium-team/+archive/ubuntu/stable, not through the Snap store which is default in 18.04.

**Comment by ahojukka5** [comment]
Just installed to Google Chrome without any problems.

**Comment by marceloakira** [comment]
I sucessfully installed it in Ubuntu 18.04.1 for chromium:
- download browserpass-linux64-<latest>.tar.gz from https://github.com/browserpass/browserpass-native/releases
- uncompress with tar: tar xvfz browserpass-linux64-<latest>.tar.gz
- cd browserpass-linux64-<latest>
- sudo cp browserpass-linux64 /usr/local/bin/browserpass
- cd browser-files
- edit chromium-host.json update path key with '/usr/local/bin/browserpass'
- cp chromium-host.json to ~/.config/chromium/native-messaging-hosts/com.github.browserpass.native.json

**Comment by KristupasSavickas** [comment]
Just a note that installing chromium as a snap is default behavior on Ubuntu 20.04 (even when using apt) and the PPA @vlazic linked above doesn't support it yet.
