### ISSUE TITLE
Uninstallation Guide

### ISSUE THREAD

**Issue by ndrewtl** [browserpass/browserpass-native#83]
This is a question, not a problem with the software. How should one go about uninstalling browserpass? I love the tool, but I installed manually and now want to go back and install with a package manager so as to streamline updates. During the process of installation, a lot of `Makefile`s seem to put a lot of things in a lot of different places. What files should I remove to constitute an uninstall? And would it be possible to write up a guide for this? Thanks for writing this, it's a fantastic tool!

**Comment by maximbaz** [comment]
Hi, glad you like it 🙂 

Uninstallation procedure basically consists of following Makefile in reverse, I realize you might be thrown off by the size of the Makefile, but you actually don't need to follow it all, only the steps that you ran.

You definitely ran `make install`, therefore step 1 is to undo everything that happens within these lines:

https://github.com/browserpass/browserpass-native/blob/6f25eaef9ea34a0218601b95fc10d557aecc13fe/Makefile#L102-L110

Assuming the standard prefixes, this would do it:

```
rm -rf /usr/bin/browserpass
rm -rf /usr/lib/browserpass
rm -rf /usr/share/doc/browserpass
rm -rf /usr/share/licenses/browserpass
```

Then you configured some of the browsers, you have to find those sections and undo them as well. Each of them would consist of removing one file, l et's say for the sake of example you are on Linux and you ran `make hosts-chromium`, in that case this was the section:

https://github.com/browserpass/browserpass-native/blob/6f25eaef9ea34a0218601b95fc10d557aecc13fe/Makefile#L115-L124

And this would be the removal:

```
rm -rf /etc/chromium/native-messaging-hosts/com.github.browserpass.native.json
```

Let me know if this makes sense and if succeeded or you have any questions?

**Comment by maximbaz** [comment]
Closing via https://github.com/browserpass/browserpass-native/commit/e2c31bdd4e39407114372b000a229836e31b1ba9
