### ISSUE TITLE
Trouble installing on openSUSE tumbleweed

### ISSUE THREAD

**Issue by NatalieGates** [browserpass/browserpass-native#88]
I installed the browser extension from chrome store and then from firefox addons. I then installed the native software for openSUSE tumbleweed. When I click the on the browserpass icon in the browser is says "error: attempt to postmessage on disconnected port" in firefox and in chrome it says "specified native messaging host not found."

I tried running `make hosts-firefox-user` and `make hosts-chrome-user` but both of those things do nothing. 

My browserpass native installation is located in usr/lib/browserpass

when I view the json file for firefox/chrome it shows the path as "/usr/bin/browserpass" Is this the issue? I tried to change the path in this file but permissions would not allow it. 

I've done this is macos several times and it works perfectly every time. I think openSUSE installations can sometimes be troublesome. Hopefully you can help me get this working.

**Comment by maximbaz** [comment]
> Is this the issue?

Yes, precisely! `make hosts-*` are nothing more but helpers that put json files in appropriate locations and set the path in these json files to the location of your binary.

Assuming openSUSE goes into [this branch of Makefile](https://github.com/browserpass/browserpass-native/blob/e2c31bdd4e39407114372b000a229836e31b1ba9/Makefile#L132), the file you need to change is `$(XDG_CONFIG_HOME)/chromium/NativeMessagingHosts/$(APP_ID).json`, which I think you should have permissions to edit.

In there you would see the `"path"` field, you need to set its value to the exact location of where you placed your `browserpass` native host executable.

https://github.com/browserpass/browserpass-native/blob/e2c31bdd4e39407114372b000a229836e31b1ba9/browser-files/chromium-host.json#L4

**Comment by Thaodan** [comment]
> Yes, precisely! `make hosts-*` are nothing more but helpers that put json files in appropriate locations and set the path in these json files to the location of your binary.

The issue is that OpenSUSE doesn't ship these files in the install prefix. Distributions such as Arch Linux move the file in place.
So the issue is either OpenSUSE because things work as intended or the bug is in the makefile for not installing them correctly.
