### ISSUE TITLE
khanacademy.org doesnt work

### ISSUE THREAD

**Issue by roberti42** [browserpass/browserpass-native#91]
### General information

-   Operating system + version: macOS 10.15.4
-   Browser + version: Firefox Developer Edition 76.0b4 (64bit)
-   Information about the host app:
    -   How did you install it? Installed using brew `amar1729/formulae`
        
    -   If installed an official release, put a version (`$ browserpass --version`): `browserpass-darwin64 --version` return "Browserpass host app version: 3.0.6"
-   Information about the browser extension:
    -   How did you install it? Installed in Firefox through `addons.mozilla.org`
        
    -   Browserpass extension version as reported by your browser: 3.4.1

---

I get no errors, other sites are working well.

---

### Exact steps to reproduce the problem

1. Insert password with `pass insert khanacademy.org/username`

2. Visit https://www.khanacademy.org/login

3. Ask browserpass to fill username and password

### What should happen?
The form should have been completed with username and password.

### What happened instead?
Only the password is filled, no username.

**Comment by maximbaz** [comment]
Thanks for reporting 🙂  Had a quick look, unfortunately looks like a won't fix, their markup is weird, username and password are placed in two different `<form>` tags 😕 With such websites Browserpass chooses to play safe and not try to fill fields it's unsure about, to avoid risk of leaking credentials to completely unrelated forms and text inputs. 

By the way, to skip having to fill out the issue template, feel free to post such examples in this thread: https://github.com/browserpass/browserpass-extension/issues/62

**Comment by roberti42** [comment]
Ok, thank you :)
