### ISSUE TITLE
Can't run make, error "no rule to make target browserpass. Stop

### ISSUE THREAD

**Issue by JJeancarlocc** [browserpass/browserpass-native#92]
### General information

-   Operating system + version: Windows 10 / Ver 1903 Build 18362.778 + WSL Ubuntu 18.04
-   Browser + version: Chrome Version 81.0.4044.122 (Build oficial) (32 bits)
-   Information about the host app:
    -   How did you install it?
        Via package manager in WSL and downloaded for Windows  following instructions in README.md
    -   If installed an official release, put a version (`$ browserpass --version`): browserpass: command not found
    -   If built from sources, put a commit id (`$ git describe --always`):
-   Information about the browser extension:
    -   How did you install it?
        Downloaded directly from google extension store
    -   Browserpass extension version as reported by your browser: 3.4.1

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

---

### Exact steps to reproduce the problem

1. Installed browserpass using package manager
 $ sudo nano /etc/apt-sources.list
 uncommented deb-src lines
 $ sudo apt-get update
 $ apt-get source webext-browserpass

2. Installed msi for windows which install a bunch of files and configuration
3. I tried running make browserpass in WSL Ubuntu and it says "make: *** no rule to make target 'browser pass'. Stop."

### What should happen?
I don't really know, I'm stucked since I Installed chrome extension but it doesn't work :(
### What happened instead?
Nothing

**Comment by maximbaz** [comment]
Hey, could you try these steps? https://github.com/browserpass/browserpass-native#install-on-windows

**Comment by JJeancarlocc** [comment]
Hi @maximbaz , I realized that README.md is different from github to README file that is installed from windows release. In the following picture in the left, it is the README.md from downloaded release version:
![No configure browser for windows](https://user-images.githubusercontent.com/23285173/80331589-0b604680-880e-11ea-9938-bdaa02057e71.jpg)
I believe this README is outdated since it is no longer necessary to configure browsers (?)
So far my steps to install on windows through WSL is:
1. Run .msi file and changed chromium-host.json file to target "browserpass-wsl"
![image](https://user-images.githubusercontent.com/23285173/80331468-c63c1480-880d-11ea-941e-368a6787e189.png)
2. Installed successfully browserpass native message hosting in WSL Ubuntu

Is there a way to check that my browserpass has been installed successfully in windows and is ready to use browserpass extension? Because Browserpass extension has an "error: error: Native host has exited."

**Comment by maximbaz** [comment]
Hi, try to follow through the full path and see if it's valid all the way: 

- Let's assume that chromium-host.json is in correct folder, open it and see the path inside, it must be full absolute path to bat file 
- open bat file and check that it runs Linux browserpass binary, again it must be full absolute path, is it correct? 

I haven't personally used browserpass in wsl, but some people reported success, therefore I think we will get to the bottom of it 👍

**Comment by JJeancarlocc** [comment]
Hi @maximbaz , yeah it was about path. I've changed bat file to and it worked ! :) 

@echo off
bash -c "/usr/bin/browserpass 2>/dev/null"

Thanks for your help!
