### ISSUE TITLE
Error: Error: Specified native messaging host not found.

### ISSUE THREAD

**Issue by alenpaul2001** [browserpass/browserpass-native#94]
### General information

-   Ubuntu 64bit + 20.04 LTS:
-   Chrome + Version 81.0.4044.129 (Official Build) (64-bit):
-   Information about the host app:
    -   latest version of browser-pass
-   How did I Installed it?
    1.  First Installed Extension
    2.  Tried using webext-browserpass but was not working
    3.  so manually downloaded native from [here](https://github.com/browserpass/browserpass-native/releases/download/3.0.6/browserpass-linux64-3.0.6.tar.gz)
    4.  extracted it and done make BIN=browserpass-linux64 configure(done without error) and 
         sudo make BIN=browserpass-linux64 install(done without error)

Result:
```
make BIN=browserpass-linux64 configure
/usr/bin/sed -i 's|"path": ".*"|"path": "'"/usr/bin/browser-linux64"'"|' browser-files/chromium-host.json
/usr/bin/sed -i 's|"path": ".*"|"path": "'"/usr/bin/browser-linux64"'"|' browser-files/firefox-host.json
```
```
sudo make BIN=browserpass-linux64 install
/usr/bin/install -Dm755 -t "/usr/bin/" browserpass-linux64
/usr/bin/install -Dm644 -t "/usr/lib/browserpass/" Makefile
/usr/bin/install -Dm644 -t "/usr/share/licenses/browserpass/" LICENSE
/usr/bin/install -Dm644 -t "/usr/share/doc/browserpass/" README.md
/usr/bin/install -Dm644 browser-files/chromium-host.json   "/usr/lib/browserpass/hosts/chromium/com.github.browserpass.native.json"
/usr/bin/install -Dm644 browser-files/chromium-policy.json "/usr/lib/browserpass/policies/chromium/com.github.browserpass.native.json"
/usr/bin/install -Dm644 browser-files/firefox-host.json    "/usr/lib/browserpass/hosts/firefox/com.github.browserpass.native.json"
```

    5.  cd to usr/lib/browserpass/ 
    6.  make hosts-chrome-user (There was no symlink errors)

### What should happen?
 Browser pass extension working
### What happened instead?
Error: Error: Specified native messaging host not found.

**Comment by maximbaz** [comment]
hey, isn't new Ubuntu using snap packages now by default? if so, this is a dup of https://github.com/browserpass/browserpass-native/issues/82

could you please confirm?

**Comment by alenpaul2001** [comment]
> hey, isn't new Ubuntu using snap packages now by default? if so, this is a dup of #82
> 
> could you please confirm?

but i dont actualy use snap store , as far as i remember i umasked snap service out

**Comment by maximbaz** [comment]
Just a random check (an idea from that other thread): could you see if you have this folder? `~/snap/chromium/`

**Comment by alenpaul2001** [comment]
Nope Below is the folder tree
```
├── canonical-livepatch
│   ├── 95
│   ├── common
│   └── current -> 95
└── snap-store
    ├── 394
    ├── 433
    ├── common
    └── current -> 433


```

**Comment by maximbaz** [comment]
Ok! Just as an idea, could you pls try system-wide browser config, i.e. `make hosts-chrome`? It seems it really depends on the distro, I can never predict which of the two will work for a given user, user-specific or system-wide 🙂

**Comment by alenpaul2001** [comment]
:smile: Already done that before posting the issue

**Comment by maximbaz** [comment]
Hmmm to be honest I dont have any other idea, you could try to double-check that everything is correct, i.e. go to `~/.config/google-chrome/NativeMessagingHosts/`, see json file, open it, see that the path to browserpass binary is correct and is valid... 🤔

**Comment by alenpaul2001** [comment]
/usr/bin/browser-linux64

no such  file or directory

**Comment by maximbaz** [comment]
Nice 👍 Sounds like `sudo make BIN=browserpass-linux64 install` didn't succeed for you after all

**Comment by maximbaz** [comment]
Ah, I see, I think you had a typo and used `BIN=browser-linux64` instead of `BIN=browserpass-linux64`

**Comment by alenpaul2001** [comment]
oh yes my bad ,

I am really soory for disturbing you.
Thanks for helping me :smile:

**Comment by maximbaz** [comment]
No worries, enjoy the extension! 🙂
